# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e3087fa4fdbb09a8dae60787ac9f393a4bb3a7113daf4c6cb0caf1e1475412f35015b8feed23f61ee0d158e4b9419e22f4d5e37490c3459e0362f0e279c50b6

test:
  secret_key_base: 16b2d3951f0980218b8f9569300d3b131cda41a2701a65117b2b21a9c6754cf84872901dce93b1f9362818c3bd037c7471f81639324507f617e86d4d5cdf7571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
